FROM golang:1.26.4-bookworm

ARG TERRAFORM_VERSION=1.14.9
ARG GOLANGCI_LINT_VERSION=v2.12.2
ARG GORELEASER_VERSION=v2.8.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    make \
    curl \
    unzip \
    jq \
    bash-completion \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
    -o /tmp/terraform.zip \
    && unzip /tmp/terraform.zip -d /usr/local/bin/ \
    && rm /tmp/terraform.zip \
    && terraform --version

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh \
    | sh -s -- -b /usr/local/bin ${GOLANGCI_LINT_VERSION}

RUN go install github.com/goreleaser/goreleaser/v2@${GORELEASER_VERSION}

RUN go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

RUN go install github.com/securego/gosec/v2/cmd/gosec@latest
RUN go install golang.org/x/vuln/cmd/govulncheck@latest

ENV CGO_ENABLED=0
ENV GOFLAGS="-mod=mod"

CMD ["sleep", "infinity"]
